spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
#        - id: route_service_one
#          uri: lb://authorization-server:8000 # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
#          predicates:
#            - Path=/**
  security:
    oauth2:
      jwt:
        signingKey: 123456

  redis:
    host: localhost
    port: 6379
    #password: ${REDIS_PASSWORD:}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.springboot.cloud.gateway: debug
    com.jalja.org.spring: debug

gate:
  ignore:
    authentication:
      startWith: /oauth,/open


